name: ChatColorPicker
main: co.purevanilla.mcplugins.ChatColorPicker.Main
version: 1.0.0
api-version: 1.13
author: quiquelhappy
commands:
  chatcolor:
    usage: "/chatcolor <color>"
    permission: chatcolorpicker.use
    description: "allows you to change your message colors"