main: co.purevanilla.mcplugins.chatcolors.ChatColors
name: ChatColors
author: quiquelhappy
version: 1.0.0
api-version: 1.18
softdepend: ["PlaceholderAPI"]
commands:
  chatcolor:
    permission: chatcolor.menu
    description: "set your chat color"
    usage: /chatcolor